### ISSUE TITLE
Timelapse save as video (captureScreen)

### ISSUE THREAD

**Issue by lukarenko** [xbgmsharp/vuestic-postgsail#130]
**Describe the feature**

Save timelapse replay to video.

We could use:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/captureStream
https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder

**Comment by xbgmsharp** [comment]
I have prototype work using chrome remote. it does require the user to allow public log details.
The first step was to create a timelapse full map, this step is complete, /maplapse

**Comment by xbgmsharp** [comment]
Task completed
