### ISSUE TITLE
Feature request: Add Eniro maps 

### ISSUE THREAD

**Issue by fymmot** [xbgmsharp/vuestic-postgsail#135]
- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] support request

- **Do you want to request a _feature_ or report a _bug_?** Feature

- **Description**

It would be nice to have support for Eniro charts, which are available for Sweden, Norway, Finland and Denmark. 

It seems to be pretty straight-forward with Leaflet, looking at the Grafana plugin **TrackMap**.

<img width="968" alt="image" src="https://github.com/user-attachments/assets/f81d0d3b-301e-4e95-ae63-b67af67350fd">

 See this PR: https://github.com/pR0Ps/grafana-trackmap-panel/pull/64 

Something like this maybe:

### leafletHelpers.js

``` javascript
export const baseMaps = function () {
  // Other maps here
  
  // Eniro sea maps (for Scandinavia)
  const eniro = L.tileLayer('https://{s}.eniro.com/geowebcache/service/tms1.0.0/nautical/{z}/{x}/{y}.png', {
    subdomains: ['map01', 'map02', 'map03', 'map04'],
    attribution: '&copy; Kort & Matrikelstyrelsen',
    tms: true,
    maxZoom: 17,
  })

  const baseMaps = {
    Satellite: sat,
    OpenStreetMap: osm,
    CARTO: cartodb,
    'Eniro (Scandinavia)': eniro,
    'Nautical charts (USA)': noaa,
    'EMODnet Bathymetry': bathymetryGroupLayer,
  }

  return baseMaps
}
```

Note: I was hoping to submit this as a PR but I haven't yet managed to get my local dev environment up and running 😅 So the code is untested. I hope you don't mind!

**Comment by xbgmsharp** [comment]
Done, pretty straight-forward.
