### ISSUE TITLE
Log average/max speed is not updated if you delete problematic track point

### ISSUE THREAD

**Issue by lukarenko** [xbgmsharp/vuestic-postgsail#145]
**Describe the bug**
I had a logbook with max speed of 25.2 kts which is much more than my boat can do.

<img width="447" alt="image" src="https://github.com/user-attachments/assets/0b9cb726-d686-4cc2-a087-7543640e7a15">

I have found the problematic track point:

<img width="576" alt="image" src="https://github.com/user-attachments/assets/3cb1d67f-1da7-49c4-9335-67e0e7e6a605">

I have removed the problematic track point, but the average and max speed of the logbook and stats did not update:
<img width="891" alt="image" src="https://github.com/user-attachments/assets/9a9ad089-81d9-43a7-8a51-d683e4688396">

**Expected behavior**
If track point is removed, logbook average and max speed should be recalculated.

**Comment by lukarenko** [comment]
@xbgmsharp can you check this one? It would be really good if user can clean problematic data out.

**Comment by xbgmsharp** [comment]
Completed
Front-end with f4e91ec9928ab286c55eb7dceddc85966390ff8a
back-end with [60e00975402869d059c8118bbddab5099b2856d4](https://github.com/xbgmsharp/postgsail/commit/60e00975402869d059c8118bbddab5099b2856d4)
