### ISSUE TITLE
Moorages Map: stay time is rounded down - 0 days stay

### ISSUE THREAD

**Issue by lukarenko** [xbgmsharp/vuestic-postgsail#150]
**Describe the bug**
Most overnight stays are just a bit less than 1 day:
<img width="1167" alt="image" src="https://github.com/user-attachments/assets/f9777ffc-e1b0-48b6-b1d5-cbdbc5d2cd70">

But on moorages map, such stays are shown as  `0 day(s) stay`:
<img width="580" alt="image" src="https://github.com/user-attachments/assets/9bef5fb3-a776-4e52-ab79-7028d7667bce">

I suggest that API returns duration string and that it is up to web UI to decide how to present it to the user.

**Comment by xbgmsharp** [comment]
The API returns ISO8601 duration string. The web UI how to decide how to present it to the user.
it show 0 day as it is less than 24h.
I updated the moorages map with a nicer popup and make at least 1 day, 01d2504a82dadc9726bd4d868622fe96f9f146b6
