### ISSUE TITLE
Refactor export function

### ISSUE THREAD

**Issue by xbgmsharp** [xbgmsharp/vuestic-postgsail#64]
Export to CSV is working, but need to update GPX (XML) handle and Geojson.
Geojosn should be without external http query.

**Comment by osipuk** [comment]
I'm ILya from peopleperhour.
I have rich experience in vue.js.
Please contact me.

**Comment by xbgmsharp** [comment]
Done with 68faeb773d4ee4a08ffed9c37109632565625998
