### ISSUE TITLE
Add Import/Export log

### ISSUE THREAD

**Issue by SailingTUSK** [xbgmsharp/vuestic-postgsail#89]
**Describe the bug**
Not a bug. 
Would be nice to be able to import old log...

**Comment by xbgmsharp** [comment]
The API and the web UI allows you to export the logs in various format CSV, GeoJson, GPX, KML
The API allow you to import logs from CSV. 
If you want to import from saillogger I created helpers to generate the metrics base on logs. https://github.com/xbgmsharp/postgsail-helpers

**Comment by SailingTUSK** [comment]
this is exactly what I'm trying to do. 
Here's my export from saillogger
[Saillogger_Logs_Export.csv](https://github.com/xbgmsharp/vuestic-postgsail/files/14065337/Saillogger_Logs_Export.csv)

**Comment by xbgmsharp** [comment]
Please reach out via Slack
