### ISSUE TITLE
Submenu dark theme  not working correctly  in minimal sidebar view

### ISSUE THREAD

**Issue by bgrr74** [xbgmsharp/vuestic-postgsail#90]
**Describe the bug**
The submenu;s do not work in the dark theme when the side bar is set to minimal.

See screenshot for details

**To Reproduce**
1 Set theme to dark
2 Open submenu item "Moorages , Monitoring  , Timelaps or Help"

**Expected behavior**
expected behavoir would be the submenu's have the dark theme and not the light theme.

**Screenshots**
![image](https://github.com/xbgmsharp/vuestic-postgsail/assets/48893544/d141e964-88f4-479e-972b-cf63ce0a8b63)

**Desktop (please complete the following information):**

- Windows 11
- Chrome
- 120.0.6099.225

**Additional context**

**Comment by xbgmsharp** [comment]
done via 93e43d188dadc4a346e9bab375f1f367d55c5b2a
